@php
    $parentId = old('parent_id', request('parent_id') ?? optional($category)->parent_id);
@endphp

<div class="row g-3">
    <div class="col-md-6">
        <label class="form-label">Name *</label>
        <input type="text" name="name" value="{{ old('name', optional($category)->name) }}" class="form-control" required>
        @error('name') <div class="text-danger small">{{ $message }}</div> @enderror
    </div>

    <div class="col-md-6">
        <label class="form-label">Slug (optional)</label>
        <input type="text" name="slug" value="{{ old('slug', optional($category)->slug) }}" class="form-control" placeholder="autogenerated from name">
        @error('slug') <div class="text-danger small">{{ $message }}</div> @enderror
    </div>

    <div class="col-md-6">
        <label class="form-label">Parent</label>
        <select name="parent_id" class="form-select">
            <option value="">— Root —</option>
            @foreach($all as $opt)
                <option value="{{ $opt->id }}" @selected($parentId == $opt->id)>{{ $opt->name }}</option>
            @endforeach
        </select>
        @error('parent_id') <div class="text-danger small">{{ $message }}</div> @enderror
    </div>

    <div class="col-md-6 d-flex align-items-end">
        <div class="form-check">
            <input type="hidden" name="is_active" value="0">
            <input class="form-check-input" type="checkbox" name="is_active" value="1"
                   id="is_active" @checked(old('is_active', optional($category)->is_active ?? true))>
            <label class="form-check-label" for="is_active">Active</label>
        </div>
    </div>

    <div class="col-12">
        <label class="form-label">Description</label>
        <textarea name="description" class="form-control" rows="3">{{ old('description', optional($category)->description) }}</textarea>
        @error('description') <div class="text-danger small">{{ $message }}</div> @enderror
    </div>
</div>
