@extends('layouts.admin')
@section('title', $title ?? 'Create product')
@section('page_title', 'Create product')

@push('page-styles')
<link rel="stylesheet" href="{{ asset('css/admin/edit_category.css') }}">
{{-- можно сделать отдельный css для форм продуктов, но этот уже даёт чистую светлую форму --}}
@endpush

@section('content')
  <form action="{{ route('admin.products.store') }}" method="POST" enctype="multipart/form-data" class="edit-form card p-3">
    @csrf

    <div class="row g-3">
      <div class="col-md-6">
        <label class="form-label">Name *</label>
        <input type="text" name="name" value="{{ old('name') }}" class="form-control" required>
        @error('name') <div class="text-danger small">{{ $message }}</div> @enderror
      </div>

      <div class="col-md-6">
        <label class="form-label">Code</label>
        <input type="text" name="code" value="{{ old('code') }}" class="form-control" placeholder="SKU / Code">
        @error('code') <div class="text-danger small">{{ $message }}</div> @enderror
      </div>

      <div class="col-md-6">
        <label class="form-label">Slug (optional)</label>
        <input type="text" name="slug" value="{{ old('slug') }}" class="form-control" placeholder="autogenerated from name">
        @error('slug') <div class="text-danger small">{{ $message }}</div> @enderror
      </div>

      <div class="col-md-6">
        <label class="form-label">Price *</label>
        <input type="number" name="price" step="0.01" min="0" value="{{ old('price') }}" class="form-control" required>
        @error('price') <div class="text-danger small">{{ $message }}</div> @enderror
      </div>

      <div class="col-md-6">
        <label class="form-label">Category</label>
        <select name="category_id" class="form-select">
          <option value="">— None —</option>
          @foreach($categories as $c)
            <option value="{{ $c->id }}" @selected(old('category_id') == $c->id)>{{ $c->name }}</option>
          @endforeach
        </select>
        @error('category_id') <div class="text-danger small">{{ $message }}</div> @enderror
      </div>

      <div class="col-md-6">
        <label class="form-label">Type</label>
        <select name="type" class="form-select">
          <option value="">— None —</option>
          @foreach($types as $t)
            <option value="{{ $t }}" @selected(old('type') === $t)>{{ $t }}</option>
          @endforeach
        </select>
        @error('type') <div class="text-danger small">{{ $message }}</div> @enderror
      </div>

      <div class="col-12">
        <label class="form-label">Description</label>
        <textarea name="description" rows="4" class="form-control">{{ old('description') }}</textarea>
        @error('description') <div class="text-danger small">{{ $message }}</div> @enderror
      </div>

      <div class="col-12">
        <label class="form-label">Images (up to 5)</label>
        <input type="file" name="images[]" class="form-control" accept="image/*" multiple>
        @error('images') <div class="text-danger small">{{ $message }}</div> @enderror
        @error('images.*') <div class="text-danger small">{{ $message }}</div> @enderror
        <div class="small" style="color:#7a8394; margin-top:6px;">JPEG/PNG/WEBP, max 5MB each.</div>
      </div>
    </div>

    <div class="mt-3">
      <button class="btn btn-primary">Create</button>
      <a href="{{ route('admin.products.index') }}" class="btn btn-secondary">Cancel</a>
    </div>
  </form>
@endsection
